routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('receiving', 'ReceivingController');
Route::resource('transaction', 'TransactionController');
Route::resource('payroll', 'PayRollController');


Route::get('/pl', 'TransactionController@profitLoss')->name('pl');
Route::post('/pl', 'TransactionController@calucalteProfitLoss')->name('pl.calculate');

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    public function company()
    {
        return $this->hasMany('App\Company');
    }
}

app/BalanceInventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BalanceInventory extends Model
{
    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    //
}

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    public function reps()
    {
        return $this->hasMany('App\CompanyRep');
    }

    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }

    public function branch()
    {
        return $this->hasMany('App\Branch');
    }
}

app/CompanyRep.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyRep extends Model
{
    public function person()
    {
        return $this->belongsTo('App\Person','people_id');
    }

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    public function person()
    {
        return $this->belongsTo('App\Person','people_id');
    }
    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    public function documentable()
    {
        return $this->morphTo();
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    public function person()
    {
        return $this->belongsTo('App\Person','people_id');
    }
    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Giving.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Giving extends Model
{
    protected $fillable = [];
}

app/PayRoll.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PayRoll extends Model
{
    public function employee()
    {
        return $this->belongsTo('App\Employee','employee_id');
    }
    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Person extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Receiving.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Receiving extends Model
{
   	protected $fillable = [];
}

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    public static function type($type)
    {
		return (string) self::where('type',$type)->first()->value;
    }
}

app/ShareHolder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ShareHolder extends Model
{
    public function person()
    {
        return $this->belongsTo('App\Person','people_id');
    }
    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
   public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'mobile',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];
}

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    public function person()
    {
        return $this->belongsTo('App\Person','people_id');
    }

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function document()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show(Branch $branch)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit(Branch $branch)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Branch $branch)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/ajax/ajax_pl.blade.php
            <div class="card">
                <div class="card-header">Sale</div>
                <div class="card-body">
                    <table class="table table-bordered">
                        @php
                            $sum = 0;
                        @endphp
                        @foreach($data['sales'] as $sale)
                            <tr>
                                <th>{{ $sale['sub_type'] }}</th>
                                <td>{{ $sale['balance'] }}</td>
                            </tr>
                            @php
                                $sum+= $sale['balance'];
                            @endphp
                        @endforeach
                        <tfoot>
                            <th>Total</th>
                            <td>{{ $sum }}</td>
                        </tfoot>
                    </table>
                </div>
            </div>
            <br>
                    <div class="card">
                        <div class="card-header">Direct Expense</div>

                        <div class="card-body">
                            <table class="table table-bordered">
                                
                                    <tr>
                                        <th>Starting Balance</th>
                                        <td>{{ $data['startingBalance'] }}</td>
                                    </tr>
                                     <tr>
                                        <th>Ending Balance</th>
                                        <td>{{ $data['endingingBalance'] }}</td>
                                    </tr>
                                     <tr>
                                        <th>Purchase</th>
                                        <td>{{ $data['purchase']->balance }}</td>
                                    </tr>
                                     <tr>
                                        <th>Total</th>
                                        <td>{{ $data['totalDirectExpense'] }}</td>
                                    </tr>
                                
                            </table>
                        </div>
                    </div>
    <br>
            <div class="card">
                <div class="card-header">Profit</div>

                <div class="card-body">
                    <table class="table table-bordered">
                            @php
                                $profit = $sum - $data['totalDirectExpense'];
                            @endphp
                            <tr>
                                <th>Profit</th>
                                <td>{{ $profit }}</td>
                            </tr>
                       
                    </table>
                </div>
            </div>
    <br>
            <div class="card">
                <div class="card-header">Indirect Expense</div>

                <div class="card-body">
                    <table class="table table-bordered">
                        @php
                            $sumIndirectExpense = 0;
                        @endphp
                        @foreach($data['indirectExpenses'] as $ie)
                            <tr>
                                <th>{{ $ie->from }}</th>
                                <td>{{ $ie->balance }}</td>
                            </tr>
                            @php
                                $sumIndirectExpense+= $ie->balance;
                            @endphp
                        @endforeach
                            @php
                                $sumIndirectExpense+= $data['salary']->balance;
                            @endphp
                            <tr>
                                <th>Salary</th>
                                <td>{{ $data['salary']->balance }}</td>
                            </tr>
                            <tfoot>
                                <th>Total</th>
                                <td>{{ $sumIndirectExpense }}</td>
                            </tfoot>
                    </table>
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-header">Net Profit</div>

                <div class="card-body">
                    <table class="table table-bordered">
                       
                            <tr>
                                <th>Gross Profit</th>
                                <td>{{ $profit - $sumIndirectExpense }}</td>
                            </tr>
                       
                    </table>
                </div>
            </div>

resources/views/cashflow.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cash in hand</div>
                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['cashinhand'] as $cashinhand)
                            <tr>
                                <th>{{ $cashinhand['party'] }}</th>
                                <td>{{ $cashinhand['amount'] }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
            <br>
                    <div class="card">
                        <div class="card-header">Credit Sales</div>

                        <div class="card-body">
                            <table class="table table-bordered">
                                @foreach($data['credit_sales'] as $credit_sales)
                                    <tr>
                                        <th>{{ $credit_sales->company }}</th>
                                        <td>{{ $credit_sales->balance }}</td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
    <br>
            <div class="card">
                <div class="card-header">Vendor Balance</div>

                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['cashflow'] as $cashflow)
                            <tr>
                                <th>{{ $cashflow->company }}</th>
                                <td>{{ $cashflow->balance }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
    <br>
            <div class="card">
                <div class="card-header">Payroll</div>

                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['payroll'] as $cashflow)
                            <tr>
                                <th>{{ $cashflow->employee }}</th>
                                <td>{{ $cashflow->balance }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('pl') }}">{{ __('Profit/Loss') }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('transaction.index') }}">{{ __('Cashflow') }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('payroll.create') }}">{{ __('Payroll') }}</a>
                                </li>
                             <li class="nav-item">
                                    <a class="nav-link" href="{{ route('receiving.create') }}">{{ __('Receiving') }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('transaction.create') }}">{{ __('Transaction') }}</a>
                                </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pl.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
            

        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Calculate</div>
                <div class="card-body">
                    {!! Form::open(['route'=>'pl.calculate','class'=>'form-material','id'=>'calucalteProfitLoss']) !!}
                        
                        <div class="row">
                            <div class="col-md-4">
                                <input type="date" name="from" class="form-control" placeholder="From">
                            </div>
                             <div class="col-md-4">
                                <input type="date" name="to" class="form-control" placeholder="To">
                            </div>
                            <div class="col-md-4">
                                <input type="submit" name="calculate" value="Go" class="btn btn-primary">
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <br>
            <div id="result">
            </div>

        </div>
    </div>
</div>

<script type="text/javascript"></script>

<script type="text/javascript">

$(document).ready(function(){
    $('#calucalteProfitLoss').submit(function () {

       $.post('{{ route("pl.calculate") }}',$(this).serialize(), function (data){
            $("#result").html(data);
       });
        return false;
    });
});
</script>
@endsection

resources/views/profit_loss.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cash in hand</div>
                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['cashinhand'] as $cashinhand)
                            <tr>
                                <th>{{ $cashinhand['party'] }}</th>
                                <td>{{ $cashinhand['amount'] }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
    <br>
            <div class="card">
                <div class="card-header">Vendor Balance</div>

                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['cashflow'] as $cashflow)
                            <tr>
                                <th>{{ $cashflow->company }}</th>
                                <td>{{ $cashflow->balance }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
    <br>
            <div class="card">
                <div class="card-header">Payroll</div>

                <div class="card-body">
                    <table class="table table-bordered">
                        @foreach($data['payroll'] as $cashflow)
                            <tr>
                                <th>{{ $cashflow->employee }}</th>
                                <td>{{ $cashflow->balance }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript"></script>
@endsection